return { read_globals = {
    "localPlayer", "triggerServerEvent", "triggerLatentServerEvent", "bindKey", "unbindKey", "getKeyState",
    "isCursorShowing", "showCursor", "getCursorPosition", "guiGetScreenSize", "dxDrawText", "dxDrawRectangle",
    "dxDrawImage", "dxDrawImageSection", "dxDrawLine", "dxDrawLine3D", "dxDrawCircle", "dxGetTextWidth",
    "dxGetFontHeight", "dxGetTextSize", "dxCreateFont", "dxCreateRenderTarget", "dxSetRenderTarget",
    "dxSetBlendMode", "dxCreateTexture", "dxGetMaterialSize", "getScreenFromWorldPosition", "isLineOfSightClear",
    "processLineOfSight", "getGroundPosition", "isElementStreamedIn", "guiCreateWindow", "guiCreateEdit",
    "guiCreateButton", "guiCreateLabel", "guiEditSetMasked", "guiGetText", "guiSetText", "guiSetVisible",
    "guiGetVisible", "guiSetInputMode", "guiSetInputEnabled", "guiWindowSetMovable", "guiWindowSetSizable",
    "guiSetProperty", "guiSetFont", "guiBringToFront", "guiSetEnabled", "addCommandHandler", "isChatBoxInputActive",
    "isConsoleActive", "isMainMenuActive", "isMTAWindowActive", "setPlayerHudComponentVisible", "setCameraMatrix",
    "setCameraTarget", "fadeCamera", "getCameraMatrix", "setCameraDrunkLevel", "setBlurLevel", "playSound",
    "playSound3D", "setSoundVolume", "getPedBonePosition", "toggleControl", "toggleAllControls",
    "setElementBonePosition", "getElementBoneMatrix", "engineLoadDFF", "engineLoadTXD", "engineLoadCOL",
    "engineReplaceModel", "engineImportTXD", "engineReplaceCOL", "engineRequestModel", "engineFreeModel",
    "setElementStreamable", "createBuilding", "removeWorldModel", "setOcclusionsEnabled", "xmlLoadFile",
    "xmlCreateFile", "xmlUnloadFile", "xmlNodeGetValue", "xmlNodeSetValue", "xmlSaveFile", "getKeyBoundToCommand",
    "setElementCollidableWith", "engineStreamingRequestModel", "getPedControlState", "setPedControlState",
    "getElementDistanceFromCentreOfMassToBaseOfModel", "setPlayerNametagShowing",
} }
