local rules = dofile("resources/[scavengesurvive]/auth/shared/logic/rules.lua")
describe("auth rules", function()
    it("validates password length 4..32", function()
        assert.is_false((rules.validatePassword("abc")))
        assert.is_true((rules.validatePassword("abcd")))
        assert.is_false((rules.validatePassword(string.rep("a", 33))))
    end)
    it("validates MTA nicknames", function()
        assert.is_true((rules.validateName("Southclaws")))
        assert.is_false((rules.validateName("has space")))
        assert.is_false((rules.validateName(string.rep("a", 23))))
    end)
end)
