local survival = dofile("resources/[scavengesurvive]/character/shared/logic/survival.lua")
local function rng(values)
    local i = 0
    return function()
        i = i + 1
        return values[((i - 1) % #values) + 1]
    end
end
describe("survival woundsOnLoad", function()
    it("keeps one wound for a real bleed so the next tick does not cure it", function()
        assert.equals(1, survival.woundsOnLoad(0.35))
        local state = { hp = 80, food = 80, bleed = 0.35, wounds = survival.woundsOnLoad(0.35) }
        local s = survival.tick(state, 1.0, rng({ 0.99 }))
        assert.is_true(s.bleed > 0)
    end)
    it("treats no bleed and the new-spawn token bleed as unwounded", function()
        assert.equals(0, survival.woundsOnLoad(0))
        assert.equals(0, survival.woundsOnLoad(survival.NEW.bleed))
        assert.equals(0, survival.woundsOnLoad(false))
    end)
end)
describe("survival deathCause", function()
    it("blames bleeding first, then hunger", function()
        assert.equals("bleeding", survival.deathCause(0.2, 10))
        assert.equals("starvation", survival.deathCause(0, 10))
        assert.equals("unknown", survival.deathCause(0, 50))
    end)
end)
describe("survival tick", function()
    it("drains food by 0.004 x movement multiplier", function()
        local s = survival.tick({ hp = 100, food = 80, bleed = 0, wounds = 0 }, 1.0, rng({ 0.99 }))
        assert.is_true(math.abs(s.food - 79.996) < 1e-6)
        s = survival.tick({ hp = 100, food = 80, bleed = 0, wounds = 0 }, 2.2, rng({ 0.99 }))
        assert.is_true(math.abs(s.food - (80 - 0.004 * 2.2)) < 1e-6)
    end)
    it("hurts when starving", function()
        local s = survival.tick({ hp = 50, food = 0, bleed = 0, wounds = 0 }, 1.0, rng({ 0.99 }))
        assert.is_true(math.abs(s.hp - (50 - 20 / 30 + 0)) < 1e-6)
    end)
    it("regenerates when not bleeding", function()
        local s = survival.tick({ hp = 50, food = 100, bleed = 0, wounds = 0 }, 1.0, rng({ 0.99 }))
        -- upstream runs food.pwn before bleed.pwn, so regen reads the already-drained food
        assert.is_true(math.abs(s.hp - (50 + 0.001925925 * (100 - 0.004))) < 1e-6)
    end)
    it("bleeds with 70% chance and slows down with wounds", function()
        local s = survival.tick({ hp = 50, food = 100, bleed = 0.2, wounds = 1 }, 1.0, rng({ 0.1, 0.1 }))
        assert.is_true(s.hp < 50)
        assert.is_true(s.bleed < 0.2)
        local t = survival.tick({ hp = 50, food = 100, bleed = 0.2, wounds = 0 }, 1.0, rng({ 0.1, 0.1 }))
        assert.equals(0, t.bleed) -- no wounds => bleeding stops (upstream guard)
    end)
    it("reports death at 0 hp", function()
        local s, events = survival.tick({ hp = 0.5, food = 0, bleed = 0, wounds = 0 }, 1.0, rng({ 0.99 }))
        assert.equals(0, s.hp)
        assert.same({ "died" }, events)
    end)
    it("classifies movement", function()
        assert.equals(0.2, survival.movementMultiplier(0, true))
        assert.equals(1.0, survival.movementMultiplier(0, false))
        assert.equals(1.2, survival.movementMultiplier(0.05, false))
        assert.equals(1.8, survival.movementMultiplier(0.11, false))
        assert.equals(2.2, survival.movementMultiplier(0.2, false))
    end)
end)
