local bars = dofile("resources/[scavengesurvive]/hud/shared/logic/bars.lua")
describe("hud bars", function()
    it("clamps fill fractions", function()
        assert.equals(1, bars.fill(150, 100))
        assert.equals(0, bars.fill(-5, 100))
        assert.equals(0.5, bars.fill(50, 100))
    end)
    it("positions bars bottom-left scaled", function()
        local l = bars.layout(1920, 1080, 1)
        assert.is_true(l.x > 0 and l.y > 900 and l.w > 100)
        local s = bars.layout(1280, 720, 720 / 1080)
        assert.is_true(s.w < l.w)
    end)
    it("darkens health when low", function()
        local r1 = select(1, bars.colour("hp", 1.0))
        local r2 = select(1, bars.colour("hp", 0.1))
        assert.is_true(r2 < r1)
    end)
end)
