local diff = dofile("resources/[scavengesurvive]/items/shared/logic/diff.lua")
describe("items diff", function()
    it("computes adds and removes against the sent set", function()
        local add, remove, sent = diff.compute({ [1] = true, [2] = true }, { { id = 2 }, { id = 3 } })
        assert.same({ { id = 3 } }, add)
        assert.same({ 1 }, remove)
        assert.same({ [2] = true, [3] = true }, sent)
    end)
end)
