local mock = require("tests.lua.helpers.mta_mock")
local load = require("tests.lua.helpers.load_module")
describe("lib.util", function()
    local util
    before_each(function() mock.install(); util = load("util") end)
    it("clamps and rounds", function()
        assert.equals(5, util.clamp(7, 0, 5)); assert.equals(0, util.clamp(-1, 0, 5))
        assert.equals(1.23, util.round(1.2345, 2)); assert.equals(2, util.round(1.5, 0))
    end)
    it("splits and counts", function()
        assert.same({ "a", "b" }, util.split("a,b", ","))
        assert.equals(2, util.tableCount({ x = 1, y = 2 }))
    end)
    it("logs through outputDebugString and outputServerLog", function()
        util.log("items", "warn", "hello %s", "world")
        assert.same({ "outputDebugString", "[items] hello world", 2 }, { mock.calls[1][1], mock.calls[1][2], mock.calls[1][3] })
        assert.equals("outputServerLog", mock.calls[2][1])
    end)
end)
