local mock = require("tests.lua.helpers.mta_mock")
local load = require("tests.lua.helpers.load_module")
describe("lib.db", function()
    local db
    before_each(function()
        mock.install()
        mock.settings = { ["lib.db_host"] = "127.0.0.1", ["lib.db_port"] = "3306", ["lib.db_name"] = "ss", ["lib.db_user"] = "u", ["lib.db_pass"] = "p" }
        db = load("db")
        assert.is_true(db.connect("items"))
    end)
    it("query passes rows to the callback with ctx", function()
        local got
        db.query("SELECT 1", {}, function(rows, ctx) got = { rows, ctx } end, { player = "p1" })
        mock.answer(1, { { n = 1 } })
        assert.same({ { { n = 1 } }, { player = "p1" } }, got)
    end)
    it("one returns nil for no rows and false on error", function()
        local a, b
        db.one("SELECT 1", {}, function(row) a = row end)
        db.one("SELECT 1", {}, function(row) b = row end)
        mock.answer(1, {})
        mock.fail(2, 1064, "syntax")
        assert.is_nil(a); assert.is_false(b)
        assert.equals("outputDebugString", mock.calls[#mock.calls - 1][1]) -- error was logged
    end)
    it("call parses the ok/code/payload row", function()
        local res
        db.call("item_pickup", { 5, 7 }, function(r) res = r end)
        assert.matches("^CALL item_pickup%(%?, %?%)$", mock.queries[1].sql)
        mock.answer(1, { { ok = 1, code = "OK", payload = '{"item_id":5}' } })
        assert.is_true(res.ok); assert.equals("OK", res.code); assert.equals(5, res.payload.item_id)
    end)
    it("call reports refusals with ok=false and a code", function()
        local res
        db.call("item_pickup", { 5, 7 }, function(r) res = r end)
        mock.answer(1, { { ok = 0, code = "HANDS_FULL", payload = false } })
        assert.is_false(res.ok); assert.equals("HANDS_FULL", res.code); assert.is_nil(res.payload)
    end)
    it("honours params.n so trailing nils still produce placeholders", function()
        db.call("item_create", { "X", nil, nil, n = 3 }, function() end)
        assert.equals("CALL item_create(?, ?, ?)", mock.queries[1].sql)
    end)
    it("uses batch=0 and a shared game queue in the connection options", function()
        assert.is_true(db.options():find("batch=0", 1, true) ~= nil)
        assert.is_true(db.options():find("queue=game", 1, true) ~= nil)
        assert.is_true(db.options():find("share=1", 1, true) ~= nil)
    end)
end)
