local map = dofile("resources/[scavengesurvive]/data/model_map.lua")
describe("model_map", function()
    it("passes vanilla ids through", function()
        local m, mapped = map.resolve(335)
        assert.equals(335, m)
        assert.is_false(mapped)
    end)
    it("maps SA-MP-only ids and falls back", function()
        assert.equals(2703, (map.resolve(19346)))
        assert.equals(map.DEFAULT, (map.resolve(19999)))
    end)
end)
