local wound = dofile("resources/[scavengesurvive]/weapons/shared/logic/wound.lua")
local function near(expected, actual) assert.is_true(math.abs(expected - actual) < 1e-9, tostring(expected) .. " ~= " .. tostring(actual)) end

describe("weapons wound", function()
    it("maps GTA weapon ids to ranges with a 35 m default", function()
        assert.equals(35, wound.range(22)); assert.equals(35, wound.range(24))
        assert.equals(40, wound.range(25)); assert.equals(40, wound.range(27))
        assert.equals(45, wound.range(29)); assert.equals(70, wound.range(30)); assert.equals(90, wound.range(31))
        assert.equals(100, wound.range(33)); assert.equals(320, wound.range(34)); assert.equals(75, wound.range(38))
        assert.equals(35, wound.range(99))
        assert.equals(2, wound.range(0)); assert.equals(2, wound.range(4)); assert.equals(2, wound.range(15)); assert.equals(35, wound.range(16))
        assert.is_true(wound.isMeleeWeapon(0)); assert.is_true(wound.isMeleeWeapon(4)); assert.is_false(wound.isMeleeWeapon(22))
        assert.is_true(wound.inRange(22, 40)); assert.is_false(wound.inRange(22, 40.1))
        assert.is_true(wound.inRange(34, 325)); assert.is_false(wound.inRange(0, 7.5))
    end)
    it("rate-limits the Desert Eagle harder than other weapons", function()
        assert.equals(790, wound.cooldown(24)); assert.equals(100, wound.cooldown(22)); assert.equals(100, wound.cooldown(0))
    end)
    it("implements the upstream firearm bleed formula", function()
        local v = 330 - 10 ^ (1 - 330 / 11300)
        near(0.25 * v / 1000 * 1.0, wound.firearm(330, 10, 0.25, 1.0))
        near(0.25 * 330 / 1000, wound.firearm(330, 0, 0.25, 1.0))
        local v2 = 900 - 150 ^ (1 - 900 / 11300)
        near(0.19 * v2 / 1000 * 2.0, wound.firearm(900, 150, 0.19, 2.0))
        assert.equals(0, wound.firearm(10, 1e6, 0.25, 1.0)) -- velocity clamped at 0
    end)
    it("applies body-part knock multipliers and the MVP headshot rule", function()
        assert.equals(1.0, wound.bodypartKnock(3)); assert.equals(1.2, wound.bodypartKnock(4))
        assert.equals(0.9, wound.bodypartKnock(5)); assert.equals(0.9, wound.bodypartKnock(6))
        assert.equals(0.8, wound.bodypartKnock(7)); assert.equals(0.8, wound.bodypartKnock(8))
        assert.equals(9.9, wound.bodypartKnock(9)); assert.equals(1.0, wound.bodypartKnock(42))
        near(0.2, wound.bodypartBleed(0.1, 9)); near(0.1, wound.bodypartBleed(0.1, 3))
        near(8.25, wound.hpLoss(0.0825))
    end)
    it("computes environmental damage as hpLoss, bleedAdd", function()
        local hp, bleed = wound.environmental(54, 50)
        near(math.min(50, 30) * 0.5, hp); near(50 * 2.5 * 0.00024, bleed)
        hp, bleed = wound.environmental(53, 20); near(10, hp); near(0, bleed)
        hp, bleed = wound.environmental(53, 4); near(4, hp)
        hp, bleed = wound.environmental(37, 40); near(40 * 0.1, hp); near(0, bleed)
        hp, bleed = wound.environmental(51, 80); near(0.5 * (80 / 80), bleed); near(0.5 * 100, hp)
        hp, bleed = wound.environmental(49, 100); near(0.04 * (100 * 0.02), bleed); near(0.04 * (100 * 0.02) * 100, hp)
        hp, bleed = wound.environmental(50, 50); near(0.04 * (50 * 0.02), bleed); near(0.04 * (50 * 0.02) * 100, hp)
        hp, bleed = wound.environmental(22, 50); near(20, hp); near(0, bleed)
        hp, bleed = wound.environmental(22, 5); near(5, hp)
    end)
    it("names causes of death", function()
        assert.equals("fall", wound.cause(54)); assert.equals("drowned", wound.cause(53)); assert.equals("burned", wound.cause(37))
        assert.equals("explosion", wound.cause(51)); assert.equals("vehicle", wound.cause(49)); assert.equals("vehicle", wound.cause(50))
        assert.equals("killed", wound.cause(22))
        assert.is_true(wound.isEnvironmental(51)); assert.is_true(wound.isEnvironmental(49)); assert.is_false(wound.isEnvironmental(22))
    end)
end)
