-- Every custom event of the MVP and whether clients may trigger it. Each resource declares the ones it uses.
return {
    onPlayerAuthenticated = false,
    onPlayerLoggedOut = false,
    onAuthRequestLogin = true,
    onAuthRequestRegister = true,
    onAuthRequestReady = true,
    onClientAuthPrompt = true,
    onClientAuthResult = true,
    onCharacterSpawned = false,
    onCharacterDied = false,
    onCharacterStatsChanged = false,
    onCharacterRequestRespawn = true,
    onClientCharacterStats = true,
    onClientCharacterDeathScreen = true,
    onItemCreated = false,
    onItemMoved = false,
    onItemDestroyed = false,
    onItemUse = false,
    onItemsRequestPickup = true,
    onItemsRequestDrop = true,
    onItemsRequestPutAway = true,
    onItemsRequestTake = true,
    onItemsRequestOpenInventory = true,
    onItemsRequestUse = true,
    onClientItemsSync = true,
    onClientItemsHeld = true,
    onClientItemsInventory = true,
    onClientItemsToast = true,
    onLootSpawned = false,
    onClientUiListAction = false,
    onClientUiListClosed = false,
    onWeaponsRequestHit = true,
    onClientWeaponsWound = true,
}
