-- Every custom event of the MVP and whether clients may trigger it. Each resource declares the ones it uses.
return {
    onPlayerAuthenticated = false,
    onPlayerLoggedOut = false,
    onAuthRequestLogin = true,
    onAuthRequestRegister = true,
    onClientAuthPrompt = false,
    onClientAuthResult = false,
    onCharacterSpawned = false,
    onCharacterDied = false,
    onCharacterStatsChanged = false,
    onCharacterRequestRespawn = true,
    onClientCharacterStats = false,
    onClientCharacterDeathScreen = false,
    onItemCreated = false,
    onItemMoved = false,
    onItemDestroyed = false,
    onItemUse = false,
    onItemsRequestPickup = true,
    onItemsRequestDrop = true,
    onItemsRequestPutAway = true,
    onItemsRequestTake = true,
    onItemsRequestOpenInventory = true,
    onItemsRequestUse = true,
    onClientItemsSync = false,
    onClientItemsHeld = false,
    onClientItemsInventory = false,
    onClientItemsToast = false,
    onLootSpawned = false,
    onClientUiListAction = false,
    onClientUiListClosed = false,
    onWeaponsRequestHit = true,
    onClientWeaponsWound = false,
}
