addEvent("onPlayerAuthenticated", false)
addEvent("onPlayerLoggedOut", false)
addEvent("onAuthRequestLogin", true)
addEvent("onAuthRequestRegister", true)
addEvent("onAuthRequestReady", true)
addEvent("onClientAuthPrompt", true)
addEvent("onClientAuthResult", true)
